name: "Install llvm toolings"
description: "Install llvm toolings like lit, FileCheck, tablegen and stuff"
inputs:
  destination:
    description: "Directory to extract the tar.xz package to"
    required: false
    default: "/usr/local"
runs:
  using: "composite"
  steps:
    # This is a hacky way to do it
    - name: Set globals
      id: globals
      shell: bash
      run: |
        echo "UBUNTU_LLVM_TOOLS=clang+llvm-18.1.7-x86_64-linux-gnu-ubuntu-18.04.tar.xz" >> "${GITHUB_OUTPUT}"
    - name: Try to at least say hi
      run: echo "hi!!!"
      shell: bash
    - name: Download llvm for ubuntu via wget
      shell: bash
      run: | 
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.7/${{ steps.globals.outputs.UBUNTU_LLVM_TOOLS }} --no-verbose
    - name: Extract and install 
      run: |
        sudo tar -xf ${{ steps.globals.outputs.UBUNTU_LLVM_TOOLS }} --directory ${{ inputs.destination }} --strip-components=1
      shell: bash

    - name: Check via ls
      run: |
        sudo ls -l ${{ inputs.destination }}/bin
        sudo ls -l ${{ inputs.destination }}/include
        sudo ls -l ${{ inputs.destination }}/lib
      shell: bash
