name: "setup-llvm-toolings"
description: "A GitHub Action to fetch LLVM toolings for your CI/CD."
inputs:
  download_path:
    description: "Full path to the llvm tooling you would want to download. For example: https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.8/clang+llvm-18.1.8-x86_64-linux-gnu-ubuntu-18.04.tar.xz"
    required: true 
  destination:
    description: "Directory to extract the tar.xz package to"
    required: false
    default: "/usr/local"
runs:
  using: "composite"
  steps:
    # This is a hacky way to do it
    - name: Set globals
      id: globals
      shell: bash
      run: |
        echo "LLVM_TOOLS=$(basename "${{ inputs.download_path }}")" >> "${GITHUB_OUTPUT}"
    - name: Try to at least say hi
      run: echo "hi!!!"
      shell: bash
    - name: Download llvm for ubuntu via wget
      shell: bash
      run: | 
        wget ${{ inputs.download_path }} --no-verbose
    - name: Extract and install 
      run: |
        sudo tar -xf ${{ steps.globals.outputs.LLVM_TOOLS }} --directory ${{ inputs.destination }} --strip-components=1
      shell: bash
    - name: Set up LLVM environment variables
      shell: bash
      run: |
        LLVM_ROOT=${{ inputs.destination }}
        echo "LLVM_ROOT_DIR=$LLVM_ROOT" >> $GITHUB_ENV
        echo "PATH=$LLVM_ROOT/bin:$PATH" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$LLVM_ROOT/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Check content via ls
      run: |
        sudo ls -l ${{ inputs.destination }}/bin
        sudo ls -l ${{ inputs.destination }}/include
        sudo ls -l ${{ inputs.destination }}/lib
      shell: bash
    - name: Check env
      shell: bash
      run: |
        echo $PATH
        echo $LLVM_ROOT_DIR
        echo $LD_LIBRARY_PATH
