name: "Install llvm toolings"
description: "Install llvm toolings like lit, FileCheck, tablegen and stuff"
inputs:
  destination:
    description: "Directory to extract the tar.xz package to"
    required: false
    default: "/usr/local"
runs:
  using: "composite"
  steps:
    - name: Try to at least say hi
      run: echo "hi!!!"
      shell: bash
    - name: Download llvm for ubuntu via wget
      shell: bash
      run: | 
        echo "clang+llvm-18.1.7-x86_64-linux-gnu-ubuntu-18.04.tar.xz" >> $UBUNTU_LLVM_TOOLS 
        wget https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.7/clang+llvm-18.1.7-x86_64-linux-gnu-ubuntu-18.04.tar.xz
    - name: Extract and install 
      run: |
        tar -xf $UBUNTU_LLVM_TOOLS --directory ${{ inputs.destination }}
      shell: bash

    - name: Check via ls
      run: |
        ls
      shell: bash
