name: Test setup llvm tools action 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Invoking the action 
      uses: ./  # Refers to the action in the current repository
      with:
        destination: "/usr/local"
    - name: Check for llvm in /usr/local
      run: |
        ls -l /usr/local/bin | grep "llvm"
        ls -l /usr/local/lib | grep "LLVM"
