name: Test setup llvm tools action 

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Invoking the action 
      uses: ./  # Refers to the action in the current repository
      with:
        destination: "/usr/local"

